### ISSUE TITLE
XCSoar/XCVario sync problems

### ISSUE THREAD

**Issue by GrahamD2** [iltis42/XCVario#141]
QNH and Bugs sync in both directions xcvario-xcsoar without problems. 
MC also is ok providing the units are set to m/s but if kts units are selected then there are issues which I think is a unit conversion calculation and/or rounding errors. 
Soar to Vario syncs 2 kts to 1.9kts, 3kts to 2.9 kts and so on.
Vario to Soar syncs 1kts to 0.6kts, 2.1 kts to 1.2 kts, 3.1 kts to 1.6 kts and so on.
Ballast soar-vario is also modified 50l to 48l, 60l - 58l 70l -68l and so on. 
vario-soar ballast change does not work at all.

Is this a bug in Xcvario or Xcsoar?

XcVario v21.1228-2019
XCsoar v7.21 Andriod 10.0.0.491 Hauwei P30 lite, driver XCvario over BT

**Comment by iltis42** [comment]
Thanks for reporting, and here my answer:
1)
Regarding MC rounding issues: Protocol limited resolution to 10th of m/s e.g. 1.0 m/s, and steps in units of m/s caused that 2 knots got rounded down in xsoar to 1.9 knots. There should nothing speak against enhancement to add more precision here to better support the way from vario to xcsor. So i extended by one digit what should fix this problem. Also the steps consider now the unit chosen, means 0.1 for m/s and 0.2 for knots. 

2)
Regarding the ballast: The way from vario to xcsoar was indeed broken, fixed that also.
Regarding the slightly lower values in vario. Agree to this finding on Android, xcsoar sents a percentage of ballast overweight, actually for my glider with max ballast 160 l if we enter 70 liter, i expect the ballast message to created like "!g,b4.375"  (10*70/160 = 4.375 ). Hence we see just "!b4.3**00**" in the data monitor. The missing 0.075 of fraction of max ballast corresponds to the lack of ballast you see in the vario. The reason for that is unknown at the moment, looks like a bug in Android version of xcsoar limiting precision roughly to about ~1%, after second digit behind comma data is lost / zeroed.  
I can't reproduce this with the latest Linux version, maybe a glitch in this xcsoar android version or a bug there.
If you feel uncomfortable with this, just open an issue with your finding for xcsoar, guess xsoar developers will also be happy about, if not already fixed, ongoing development may benefit from that finding.

The vario enhancement for  1) and the fix for the broken ballast  2) is in here:  
https://github.com/iltis42/XCVario/blob/master/images/sensor-master-21.1230-1736.bin
