### ISSUE TITLE
s2f push button sluggish

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#171]
My XCV dev device reacts sluggish and not always on the s2f mode switch button. It is setup as push button to toggle the s2f mode.

Connect a push button to S1. Setup as s2f toggle. Try to toggle s2f mode.

The circle/arrow icon should change reliable and immediately on every button press.

The non reliable switch seems to be present since the serial-dev branch got merged.

**Comment by iltis42** [comment]
The issue came in recently with the ongoing development for new S2F modes "Flap" and AHRS-Gyro, where the high frequency sceduling of 100 Hz was lowered to 10 Hz one level too high in hierarchy. Fixed that now by changeset:
https://github.com/iltis42/XCVario/commit/f5910be50d075a920da6838c1da77b42c337daa0
