### ISSUE TITLE
Sync temperature to client directly after boot

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#205]
Switching on my two seater setup the temperature does show on the client only as "--°". no temperature.

I would expect the same temp value as on the master device.

XCV Versions 22.0824-23

The issue resolved with the first temp change. Then the new value gets propagated. Would be just nice to have it propagated even after booting up the devices.

**Comment by iltis42** [comment]
Will add an update upon connection established for next release

**Comment by iltis42** [comment]
The CAN connection survived a restart of the client device due to long timeout. Increased the budget for timeout timer at failed keep alive or NMEA send messages, and the issues was gone. Changes:
https://github.com/iltis42/XCVario/commit/9d4917b32246e42dfe8650bc3b3c4db02127b139
https://github.com/iltis42/XCVario/commit/0dfb0dcb491b4df2792c19b0b09dd354064fe282

**Comment by hjr** [comment]
Could confirm this is fixed.
