### ISSUE TITLE
AHRS Autozero config unclear

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#231]
**The thing that could work better**
The human interface to the AHRS Autozero configuration is not clear, or misleading.                                        

**The current experience**
By default when activating AHRS the menu shows an entry: AHRS Autozero: Cancel
There is just the on option the change it to "Start", obviously when wings are leveled etc. as the little help text explaines.
But the expectations to what is the further process is unclear and the config menu does not give any clue. How long does it take to complete the zero capture? No progress bar no hint. I let the configuration sit on "Start" and put the wing down after a couple seconds. Talking to Ralph, he decided to switch the config item back to "cancel" before putting the wing down. Obviously we both got lost, the manual does not help on this topic.

**Expected behavior**
I would like to see a progress (bar) after selecting start. Generally the config item "Autozero" would more suggest a On/Off option. Maybe it is a unhappy combination out of Autoconfiguration On/Off and an initial "on the ground" zero capture, that should not be coupled together at all into one config item. Just guessing here.

**Additional context**
Observed on 23.0513-21 firmware revision.

**Comment by iltis42** [comment]
I think the issue was that with the last change to support the new "restart on exit", no more direct restart took place. This change: https://github.com/iltis42/XCVario/commit/6d885d9f576ed75bfa445492fbefe825bd564798 shall solve the issue. 
Pressing "Start" immediately wiped out the previous calibration, hence the calibration took place at boot (part of the selftest), and this was decoupled as of this problem. So this change now this happens again immediate and won't require progress bars or something to decouple. Its also documented in this help that a restart (restarts) will take place, unfortunately this did only happen here on exit of the menu (the new feature for e.g. serial wires where several adjustments may be needed), what caused this irritation.

**Comment by hjr** [comment]
Ok, not fully understand. My expectation would be that the calibration takes place immediately when pressing the button. Th.m. some averaged IMU samples are collected and the calibration parameters calculated and saved into flash memory. 
I would accept that the new calibration takes effect after another boot. But I definitely feel uncomfortable with a reboot to start the calibration process. That's wired. I see many wings already half ways down to the ground until this finally happens.
What am I missing here? User interaction still not entirely clear to me.

**Comment by iltis42** [comment]
IMHO nothing, as the reboot now immediately takes place
