### ISSUE TITLE
Sound server for XCSoar (improvement)

### ISSUE THREAD

**Issue by hjr** [iltis42/XCVario#39]
Some Andoird devices, specifically the nice reflective display eReaders, do not have an own speaker, rather expecting to operate with a connected sound sink.
It would be generally great to have this offered through the XCV that has a speaker, or might be connected to the cockpit speaker system. 
Most meaningful warnings like airspace warnings would then be acoustically present also for the designed silent Android devices. 

It would be nice to build on existing protocols, even other solution with potential less code footprint would be viable.

**Comment by iltis42** [comment]
A sound server needed also some interface, hence when using wifi, bluetooth is no option and when using bluetooth its configured as bluetooth/serial interface and there is no option to run a second protocol for audio via that.
So lacking an interface e.g. external audio in, the issue is closed to the current hardware. For a future hardware design, it may be an option to add new interface for external audio.
